//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj_Alissez_Estetica
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Procedimiento
    {
        public int id { get; set; }
        public int id_procedimiento { get; set; }
        public int id_producto { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> valor_cobrado { get; set; }
    
        public virtual Procedimiento Procedimiento { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
